# Generated by Django 5.2.1 on 2025-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_eixo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustivel', models.CharField(choices=[('Eletrico', 'Eletrico'), ('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Hibrido', 'Hibrido')], default='Gasolina', max_length=50)),
                ('numero_portas', models.IntegerField()),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_do_carro', models.CharField(choices=[('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('Coupé', 'Coupé'), ('SUV', 'SUV'), ('Picape', 'Picape'), ('Conversível', 'Conversível')], default='Sedan', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Eletrico', 'Eletrico')], default='Gasolina', max_length=50)),
                ('cilindrada', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
