# Generated by Django 5.2.1 on 2025-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Etanol', 'Etanol'), ('Gasolina', 'Gasolina'), ('Hibrido', 'Hibrido'), ('Flex', 'Flex'), ('Eletrico', 'Eletrico')], default='Gasolina', max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_do_carro',
            field=models.CharField(choices=[('Conversivel', 'Conversível'), ('Picape', 'Picape'), ('Hatch', 'Hatch'), ('Coupe', 'Coupé'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Etanol', 'Etanol'), ('Gasolina', 'Gasolina'), ('Eletrico', 'Eletrico')], default='Gasolina', max_length=50),
        ),
    ]
