# Generated by Django 5.2.1 on 2025-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automoveis', '0002_alter_carro_tipo_combustivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='moto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Etanol', 'Etanol'), ('Eletrico', 'Eletrico'), ('Hibrido', 'Hibrido'), ('Diesel', 'Diesel'), ('Flex', 'Flex'), ('Gasolina', 'Gasolina')], default='Gasolina', max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_do_carro',
            field=models.CharField(choices=[('Conversivel', 'Conversível'), ('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Picape', 'Picape'), ('Coupe', 'Coupé')], default='Sedan', max_length=50),
        ),
    ]
